name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: "MW ${{ matrix.mw }}, PHP ${{ matrix.php }}"

    strategy:
      matrix:
        include:
          - mw: 'master'
            php: 7.4
          - mw: 'REL1_35'
            php: 7.4
          - mw: 'REL1_34'
            php: 7.3

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mediawiki

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          tools: composer

      - name: Cache MediaWiki
        id: cache-mediawiki
        uses: actions/cache@v2
        with:
          path: |
            mediawiki
            !mediawiki/extensions/
            !mediawiki/vendor/
          key: mw_${{ matrix.mw }}-php${{ matrix.php }}-v21

      - name: Cache Composer cache
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: composer-php${{ matrix.php }}

      - uses: actions/checkout@v2
        with:
          path: EarlyCopy

      - name: Install MediaWiki
        if: steps.cache-mediawiki.outputs.cache-hit != 'true'
        working-directory: ~
        run: bash EarlyCopy/.github/workflows/installMediaWiki.sh ${{ matrix.mw }}

      - name: Composer require
        run: composer require professional-wiki/wikibase-bundle:dev-master

      - name: Run PHPUnit
        run: |
          pwd
          ls -lap
          ls -lap extensions
          ls -lap extensions/WikibaseBundle
          php tests/phpunit/phpunit.php extensions/WikibaseBundle/tests/


